import { ApiProperty } from '@nestjs/swagger';

export class UploadResponseDto {
  @ApiProperty({
    description: 'Direct URL to the uploaded file',
    example: 'https://ik.imagekit.io/your_id/vdcd/images/image.png',
  })
  url: string;

  @ApiProperty({
    description: 'The unique file ID in ImageKit',
    example: '64b0f12c...',
  })
  fileId: string;

  @ApiProperty({
    description: 'The file name',
    example: '1689395200000-abcd1234.png',
  })
  name: string;

  @ApiProperty({
    description: 'File size in bytes',
    example: 1048576,
  })
  size: number;

  @ApiProperty({
    description: 'Width of the image (if applicable)',
    example: 800,
    required: false,
  })
  width?: number;

  @ApiProperty({
    description: 'Height of the image (if applicable)',
    example: 600,
    required: false,
  })
  height?: number;

  @ApiProperty({
    description: 'The path to the file in ImageKit',
    example: '/vdcd/images/1689395200000-abcd1234.png',
  })
  filePath: string;
}

export class ImageKitAuthDto {
  @ApiProperty({
    description: 'The token generated by ImageKit for authorization',
    example: 'ab4dfg23-12cd-45ef-89gh-1234567890ab',
  })
  token: string;

  @ApiProperty({
    description: 'The signature generated for client-side upload',
    example: 'd9b7f5c228fa4c...',
  })
  signature: string;

  @ApiProperty({
    description: 'Timestamp when this token expires',
    example: 1689398800,
  })
  expire: number;
}

export class TransformedUrlDto {
  @ApiProperty({
    description:
      'The generated ImageKit URL with requested transformations applied',
    example:
      'https://ik.imagekit.io/your_id/tr:w-300,h-200,q-80,f-webp/vdcd/images/image.png',
  })
  url: string;
}
